from dataclasses import dataclass


@dataclass(frozen=True)
class TestCase:
    input: str
    output: str
    hidden: bool = False


@dataclass(frozen=True)
class Problem:
    id: str
    title: str
    difficulty: str
    tags: list[str]
    statement: str
    input_format: str
    output_format: str
    constraints: str
    samples: list[TestCase]
    tests: list[TestCase]
    time_limit_ms: int = 2000
    memory_limit_mb: int = 128


def make_problem(
    problem_id: str,
    title: str,
    difficulty: str,
    tags: list[str],
    statement: str,
    input_format: str,
    output_format: str,
    constraints: str,
    sample_input: str,
    sample_output: str,
    hidden_cases: list[tuple[str, str]],
) -> Problem:
    sample = TestCase(sample_input, sample_output)
    return Problem(
        id=problem_id,
        title=title,
        difficulty=difficulty,
        tags=["贪心", *tags],
        statement=statement,
        input_format=input_format,
        output_format=output_format,
        constraints=constraints,
        samples=[sample],
        tests=[sample, *(TestCase(data, answer, hidden=True) for data, answer in hidden_cases)],
    )


GREEDY_PROBLEMS: dict[str, Problem] = {
    "greedy-select-k-largest": make_problem(
        "greedy-select-k-largest",
        "选择 k 个数的最大和",
        "入门",
        ["局部最优", "排序"],
        "给定 n 个整数，请恰好选择其中 k 个数，使它们的和最大，输出这个最大和。",
        "第一行两个整数 n、k；第二行 n 个整数。",
        "输出能够得到的最大和。",
        "1 <= k <= n <= 100000；每个数绝对值不超过 10^9。",
        "5 2\n1 9 3 7 2\n",
        "16\n",
        [("1 1\n-5\n", "-5\n"), ("5 3\n-1 -2 -3 -4 -5\n", "-6\n"), ("6 4\n10 10 1 2 3 4\n", "27\n")],
    ),
    "greedy-coin-greedy-vs-optimal": make_problem(
        "greedy-coin-greedy-vs-optimal",
        "贪心找零与最优找零",
        "进阶",
        ["找零", "反例", "动态规划"],
        "给定一组无限供应的正整数币值和目标金额。先按币值从大到小执行贪心找零，再用动态规划求真正的最少硬币数。无法凑出时对应结果输出 -1。",
        "第一行 n 和 amount；第二行 n 个互不相同的币值。",
        "依次输出贪心硬币数和最优硬币数，以空格分隔。",
        "1 <= n <= 20，1 <= amount <= 10000，1 <= coin <= amount。",
        "3 6\n1 3 4\n",
        "3 2\n",
        [("3 18\n1 5 10\n", "5 5\n"), ("2 7\n2 4\n", "-1 -1\n"), ("4 11\n1 5 6 9\n", "3 2\n")],
    ),
    "greedy-max-affordable-count": make_problem(
        "greedy-max-affordable-count",
        "预算内购买最多物品",
        "入门",
        ["候选集", "预算", "排序"],
        "每件物品最多购买一次。给定预算和每件物品的价格，求最多能购买多少件物品。",
        "第一行 n 和 budget；第二行 n 个正整数价格。",
        "输出最多购买件数。",
        "1 <= n <= 100000，0 <= budget <= 10^18，价格不超过 10^9。",
        "5 6\n3 1 2 5 4\n",
        "3\n",
        [("3 0\n1 2 3\n", "0\n"), ("4 100\n5 5 5 5\n", "4\n"), ("6 10\n8 1 1 1 1 1\n", "5\n")],
    ),
    "greedy-select-k-values": make_problem(
        "greedy-select-k-values",
        "输出最大的 k 个数",
        "基础",
        ["候选集", "排序", "输出"],
        "给定 n 个整数，输出其中最大的 k 个数，并按从大到小的顺序排列。重复值视为不同元素。",
        "第一行 n、k；第二行 n 个整数。",
        "一行输出 k 个整数，相邻数字以一个空格分隔。",
        "1 <= k <= n <= 100000；整数绝对值不超过 10^9。",
        "6 3\n4 9 1 9 2 7\n",
        "9 9 7\n",
        [("1 1\n-3\n", "-3\n"), ("5 5\n5 4 3 2 1\n", "5 4 3 2 1\n"), ("4 2\n-5 -1 -3 -2\n", "-1 -2\n")],
    ),
    "greedy-min-dot-product": make_problem(
        "greedy-min-dot-product",
        "最小点积",
        "基础",
        ["排序", "交换论证"],
        "可以任意重排两个长度为 n 的整数序列。求对应位置乘积之和的最小值。",
        "第一行 n；第二、三行分别是两个序列。",
        "输出最小点积。",
        "1 <= n <= 100000；元素绝对值不超过 10^6。",
        "3\n1 3 -5\n-2 4 1\n",
        "-25\n",
        [("1\n7\n-2\n", "-14\n"), ("4\n1 2 3 4\n1 2 3 4\n", "20\n"), ("3\n-1 -2 -3\n-4 -5 -6\n", "28\n")],
    ),
    "greedy-smallest-concatenation": make_problem(
        "greedy-smallest-concatenation",
        "拼接最小数",
        "进阶",
        ["排序", "自定义比较器", "字符串"],
        "给定 n 个不含前导零的非负整数字符串，调整它们的顺序，使直接拼接得到的字符串字典序最小。结果保留输入数字本身的零。",
        "第一行 n；第二行 n 个数字字符串。",
        "输出最小拼接结果。",
        "1 <= n <= 10000；所有字符串总长度不超过 200000。",
        "5\n3 30 34 5 9\n",
        "3033459\n",
        [("2\n10 2\n", "102\n"), ("3\n0 0 0\n", "000\n"), ("4\n12 121 9 90\n", "12112909\n")],
    ),
    "greedy-activity-count": make_problem(
        "greedy-activity-count",
        "最多不冲突活动",
        "入门",
        ["活动选择", "区间", "最早结束"],
        "给定 n 个半开活动区间 [start,end)。同一时刻只能参加一个活动，求最多能参加多少个。结束时刻等于下一个开始时刻不冲突。",
        "第一行 n；随后 n 行每行 start 和 end。",
        "输出最多活动数。",
        "1 <= n <= 200000，-10^9 <= start < end <= 10^9。",
        "5\n1 3\n2 5\n4 6\n6 7\n5 8\n",
        "3\n",
        [("1\n0 10\n", "1\n"), ("4\n1 2\n2 3\n3 4\n4 5\n", "4\n"), ("3\n1 10\n2 9\n3 8\n", "1\n")],
    ),
    "greedy-activity-ids": make_problem(
        "greedy-activity-ids",
        "输出被选择的活动编号",
        "基础",
        ["活动选择", "原编号", "稳定规则"],
        "按结束时间从早到晚执行活动选择。结束时间相同时按输入编号小的在前。输出所选活动数量和依次选中的原编号。",
        "第一行 n；随后 n 行每行 start 和 end，编号从 1 开始。",
        "第一行输出数量；第二行输出所选编号，以空格分隔。",
        "1 <= n <= 100000，-10^9 <= start < end <= 10^9。",
        "5\n1 3\n2 5\n4 6\n6 7\n5 8\n",
        "3\n1 3 4\n",
        [("1\n0 1\n", "1\n1\n"), ("3\n0 2\n0 2\n2 3\n", "2\n1 3\n"), ("4\n1 2\n2 3\n3 4\n4 5\n", "4\n1 2 3 4\n")],
    ),
    "greedy-interval-cover-count": make_problem(
        "greedy-interval-cover-count",
        "最少区间覆盖目标线段",
        "基础",
        ["区间覆盖", "最远右端点"],
        "从给定区间中选择尽量少的区间，连续覆盖目标线段 [L,R]。区间端点相接视为连续。无法覆盖输出 -1。",
        "第一行 n、L、R；随后 n 行每行一个区间的左右端点。",
        "输出最少区间数，或 -1。",
        "1 <= n <= 200000，-10^9 <= left < right <= 10^9，L < R。",
        "4 0 10\n0 2\n1 5\n4 7\n6 10\n",
        "4\n",
        [("3 0 10\n-1 4\n2 8\n7 12\n", "3\n"), ("2 0 5\n0 2\n3 5\n", "-1\n"), ("3 0 5\n-2 10\n0 1\n1 3\n", "1\n")],
    ),
    "greedy-interval-point-cover": make_problem(
        "greedy-interval-point-cover",
        "最少点覆盖所有区间",
        "进阶",
        ["区间", "右端点", "落点"],
        "在数轴上选择尽量少的整数点，使每个闭区间 [left,right] 至少包含一个所选点。求最少点数。",
        "第一行 n；随后 n 行每行 left 和 right，端点均为整数。",
        "输出最少点数。",
        "1 <= n <= 200000，-10^9 <= left <= right <= 10^9。",
        "3\n1 3\n2 5\n4 6\n",
        "2\n",
        [("3\n1 10\n2 9\n3 8\n", "1\n"), ("4\n1 1\n2 2\n3 3\n4 4\n", "4\n"), ("4\n-3 0\n0 2\n2 4\n4 6\n", "2\n")],
    ),
    "greedy-water-total-wait": make_problem(
        "greedy-water-total-wait",
        "最小总等待时间",
        "入门",
        ["排队接水", "短任务优先", "贡献"],
        "n 个人共用一个水龙头，第 i 个人接水需要 t_i 时间。调整排队顺序，使所有人的等待时间之和最小。第一个人的等待时间为 0。",
        "第一行 n；第二行 n 个接水时间。",
        "输出最小总等待时间。",
        "1 <= n <= 200000，1 <= t_i <= 10^9。",
        "4\n3 1 4 2\n",
        "10\n",
        [("1\n99\n", "0\n"), ("3\n5 5 5\n", "15\n"), ("5\n1 2 3 4 5\n", "20\n")],
    ),
    "greedy-water-order-average": make_problem(
        "greedy-water-order-average",
        "接水顺序与平均等待",
        "基础",
        ["排队接水", "稳定排序", "平均值"],
        "输出最小化等待时间的排队编号，以及平均等待时间。接水时间相同时编号小者在前，编号从 1 开始。",
        "第一行 n；第二行 n 个接水时间。",
        "第一行输出编号；第二行输出平均等待时间，保留两位小数。",
        "1 <= n <= 100000，1 <= t_i <= 10^9。",
        "4\n3 1 4 2\n",
        "2 4 1 3\n2.50\n",
        [("1\n7\n", "1\n0.00\n"), ("3\n5 5 5\n", "1 2 3\n5.00\n"), ("3\n10 1 2\n", "2 3 1\n1.33\n")],
    ),
    "greedy-standard-change": make_problem(
        "greedy-standard-change",
        "标准币制最少找零",
        "入门",
        ["找零", "标准币制"],
        "使用面额 100、50、20、10、5、1 的无限硬币为给定金额找零，输出所需的最少硬币数。",
        "一行一个非负整数 amount。",
        "输出最少硬币数。",
        "0 <= amount <= 10^9。",
        "186\n",
        "6\n",
        [("0\n", "0\n"), ("99\n", "8\n"), ("1000\n", "10\n")],
    ),
    "greedy-boats-count": make_problem(
        "greedy-boats-count",
        "最少救生艇",
        "基础",
        ["双指针", "轻重配对"],
        "每条船最多坐两人且总重量不能超过 limit。给定每个人的体重，求运走所有人需要的最少船数。保证每个人都不超过限重。",
        "第一行 n 和 limit；第二行 n 个体重。",
        "输出最少船数。",
        "1 <= n <= 200000，1 <= weight_i <= limit <= 10^9。",
        "4 5\n1 2 2 3\n",
        "2\n",
        [("1 10\n10\n", "1\n"), ("4 5\n3 3 3 3\n", "4\n"), ("5 6\n1 2 3 4 5\n", "3\n")],
    ),
    "greedy-boats-pair-solo": make_problem(
        "greedy-boats-pair-solo",
        "统计双人船与单人船",
        "基础",
        ["双指针", "过程统计"],
        "按最优轻重配对策略运走所有人。输出其中双人船数量和单人船数量。每条船最多两人。",
        "第一行 n 和 limit；第二行 n 个体重。",
        "输出双人船数量和单人船数量。",
        "1 <= n <= 200000，1 <= weight_i <= limit <= 10^9。",
        "4 5\n1 2 2 3\n",
        "2 0\n",
        [("1 10\n10\n", "0 1\n"), ("4 5\n3 3 3 3\n", "0 4\n"), ("5 6\n1 2 3 4 5\n", "2 1\n")],
    ),
    "greedy-fractional-knapsack": make_problem(
        "greedy-fractional-knapsack",
        "可分割背包",
        "基础",
        ["单位价值", "交换论证"],
        "每件物品有重量和价值，可以拿走任意比例。背包容量有限，求能获得的最大价值。",
        "第一行 n 和容量；随后 n 行每行重量和价值，均为正整数。",
        "输出最大价值，保留两位小数。",
        "1 <= n <= 100000，容量、重量、价值均不超过 10^9。",
        "3 50\n10 60\n20 100\n30 120\n",
        "240.00\n",
        [("1 5\n10 100\n", "50.00\n"), ("2 10\n5 10\n5 20\n", "30.00\n"), ("2 3\n2 3\n2 5\n", "6.50\n")],
    ),
    "greedy-deadline-max-tasks": make_problem(
        "greedy-deadline-max-tasks",
        "截止时间内完成最多任务",
        "进阶",
        ["截止时间", "优先队列", "后悔贪心"],
        "所有任务从时刻 0 开始串行执行，任务有耗时 duration 和截止时刻 deadline。任务必须在自己的截止时刻前完成，求最多能完成多少个任务。",
        "第一行 n；随后 n 行 duration 和 deadline。",
        "输出最多任务数。",
        "1 <= n <= 200000，1 <= duration, deadline <= 10^9。",
        "4\n3 4\n2 3\n1 2\n2 6\n",
        "3\n",
        [("1\n5 4\n", "0\n"), ("3\n1 1\n1 2\n1 3\n", "3\n"), ("4\n5 5\n4 5\n3 5\n2 5\n", "2\n")],
    ),
    "greedy-min-refuels": make_problem(
        "greedy-min-refuels",
        "最少加油次数",
        "进阶",
        ["优先队列", "延迟决策", "可达范围"],
        "汽车从位置 0 出发驶向 target，初始油量 fuel，每单位油行驶一单位距离。路上每个加油站只能使用一次，可获得给定油量。求最少加油次数，无法到达输出 -1。",
        "第一行 n、target、fuel；随后 n 行 position 和 supply。",
        "输出最少加油次数，或 -1。",
        "0 <= n <= 200000，1 <= target <= 10^9，0 <= fuel <= 10^9；加油站位置在 (0,target) 内。",
        "4 100 10\n10 60\n20 30\n30 30\n60 40\n",
        "2\n",
        [("0 10 10\n", "0\n"), ("1 100 10\n20 100\n", "-1\n"), ("3 50 25\n10 10\n20 20\n30 30\n", "2\n")],
    ),
    "greedy-merge-interval-groups": make_problem(
        "greedy-merge-interval-groups",
        "合并区间后的段数",
        "基础",
        ["区间", "排序", "扫描"],
        "合并所有有交集或端点相接的闭区间，输出合并后剩余的连续区间段数。",
        "第一行 n；随后 n 行每行 left 和 right。",
        "输出合并后的区间段数。",
        "1 <= n <= 200000，-10^9 <= left <= right <= 10^9。",
        "5\n1 3\n2 6\n8 10\n10 12\n20 21\n",
        "3\n",
        [("1\n0 0\n", "1\n"), ("4\n1 2\n3 4\n5 6\n7 8\n", "4\n"), ("3\n-5 10\n-2 3\n0 1\n", "1\n")],
    ),
}
